# Generated by Django 4.2.13 on 2024-05-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membrebureauregional',
            name='id',
        ),
        migrations.RemoveField(
            model_name='membrebureauregional',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='membrebureauregional',
            name='prenom',
        ),
        migrations.AddField(
            model_name='membrebureauregional',
            name='jeune_ptr',
            field=models.OneToOneField(auto_created=True, default='Aucun', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nombres.jeune'),
            preserve_default=False,
        ),
    ]
